version: '3'
services: 
  caddy:
    image: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    hostname: caddy
    restart: unless-stopped
    depends_on:
      - filebrowser
  filebrowser:
    image: filebrowser/filebrowser
    expose: 
      - '80'
    volumes:
      - ./filebrowser/file:/srv
      - ./filebrowser/filebrowser.db:/database.db
#      - ./filebrowser.json:/.filebrowser.json
    hostname: filebrowser
    restart: unless-stopped
